name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.6"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mongomock
          pip install -r requirements.txt

      - name: Lint Python code
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "."
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-flake8-options: "--exit-zero --max-line-length=127"

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          tag=${GITHUB_REF#refs/tags/}
          username=${{ secrets.DOCKER_USERNAME }}
          docker build -t $username/vie-back:$tag .
          docker push $username/vie-back:$tag

  change-image-tag:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    environment: ci
    permissions:
      contents: write
      pull-requests: write 
      issues: write
    env:
      TAG: ${GITHUB_REF#refs/tags/}
    steps:
      - uses: actions/checkout@v4
        name: Change the deployment of git repo
        with:
          repository: smugikity/vdt-config-api
          token: ${{ secrets.GIT_TOKENN }}
          ref: main
      - name: Change image tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo $TAG
          echo “Working Directory: $(pwd)”
          sed -i "s/^ *tag:.*$/  tag: $TAG/" values.yaml
          # Print values.yaml for debugging after changes
          # echo “After modification:”
          # cat values.yaml  

      - name: Publish new image
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          # rm values.yaml.bak
          git add values.yaml
          git commit -m "Update image tag, manifest: ${{ github.run_number }}"
          git push 

